# Generated by Django 6.0.2 on 2026-02-10 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.DecimalField(decimal_places=2, max_digits=10)),
                ('green', models.DecimalField(decimal_places=2, max_digits=10)),
                ('blue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lux', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
