# Generated by Django 6.0.2 on 2026-03-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='raw_light',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
