# Generated by Django 6.0.2 on 2026-03-08 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_service', '0002_sensordata_raw_light'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='blue',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='green',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='lux',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='raw_light',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='red',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temp',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='MAC Address ESP32', max_length=50)),
                ('device_name', models.CharField(help_text='AP_SSID dari firmware', max_length=100)),
                ('ip_local', models.CharField(help_text='IP lokal di jaringan WiFi', max_length=45)),
                ('ssid', models.CharField(blank=True, help_text='Nama WiFi yang dipakai', max_length=100)),
                ('rssi', models.IntegerField(default=0, help_text='Kekuatan sinyal WiFi (dBm)')),
                ('firmware', models.CharField(blank=True, max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Diperbarui otomatis tiap heartbeat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IoT Device',
                'verbose_name_plural': 'IoT Devices',
                'ordering': ['-last_seen'],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
