# Generated by Django 6.0.2 on 2026-04-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_service', '0003_alter_sensordata_blue_alter_sensordata_green_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevice',
            name='target_status',
            field=models.BooleanField(default=False, help_text='True = Mesin ON, False = Mesin OFF'),
        ),
    ]
