# Generated by Django 6.0.2 on 2026-04-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_service', '0004_iotdevice_target_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotdevice',
            name='target_status',
            field=models.BooleanField(default=False, help_text='True = Mesin ON, False = Mesin OFF', null=True),
        ),
    ]
