# Generated by Django 6.0.2 on 2026-05-29 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_service', '0005_alter_iotdevice_target_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_device', to='iot_service.iotdevice'),
        ),
        migrations.AlterField(
            model_name='iotdevice',
            name='target_status',
            field=models.BooleanField(default=True, help_text='True = Mesin ON, False = Mesin OFF'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExperimentRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nama Eksperimen', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_device', to='iot_service.iotdevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
