# Generated by Django 6.0.2 on 2026-05-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_service', '0006_sensordata_device_alter_iotdevice_target_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentroom',
            name='name',
            field=models.CharField(blank=True, help_text='Nama Eksperimen', max_length=255),
        ),
    ]
