# Generated by Django 6.0.2 on 2026-07-04 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_service', '0008_sensordata_experiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentroom',
            name='device_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_device', to='iot_service.iotdevice'),
        ),
    ]
