# Generated by Django 6.0.2 on 2026-07-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_service', '0009_alter_experimentroom_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevice',
            name='is_sterile',
            field=models.BooleanField(default=False, help_text='True jika air terdeteksi sudah jernih/steril'),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='sterile_balance_max',
            field=models.FloatField(default=0.15, help_text='Maks selisih rasio RGB (0.0–1.0) untuk dianggap seimbang/jernih'),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='sterile_confirm_count',
            field=models.IntegerField(default=3, help_text='Berapa kali berturut-turut harus terdeteksi jernih sebelum mesin dimatikan'),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='sterile_current_count',
            field=models.IntegerField(default=0, help_text='Counter saat ini — reset saat tidak jernih'),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='sterile_lux_min',
            field=models.FloatField(default=300.0, help_text='Lux minimum agar dianggap jernih'),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='sterile_raw_min',
            field=models.FloatField(default=800.0, help_text='Raw light minimum agar dianggap jernih'),
        ),
    ]
