# Generated by Django 6.0.2 on 2026-07-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_service', '0010_add_sterile_fields_to_iotdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotdevice',
            name='target_status',
            field=models.BooleanField(default=False, help_text='True = Mesin ON, False = Mesin OFF/standby'),
        ),
    ]
