# Generated by Django 6.0.2 on 2026-07-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_service', '0012_iotdevice_active_experiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentroom',
            name='flow_speed',
            field=models.FloatField(blank=True, help_text='Flow speed target (L/s)', null=True),
        ),
        migrations.AddField(
            model_name='experimentroom',
            name='ph_target',
            field=models.FloatField(blank=True, help_text='pH target', null=True),
        ),
        migrations.AddField(
            model_name='experimentroom',
            name='suhu',
            field=models.FloatField(blank=True, help_text='Suhu target (°C)', null=True),
        ),
    ]
